# TO BUILD:
# docker build . -t test -f ./spark/dockerfile
# TO RUN:
# docker run -it test

# TODO fix the ENV variables and symbolic links

FROM ubuntu:latest
MAINTAINER Jack Skrable "https://github.com/jskrable"

# set shell to use bash
SHELL ["/bin/bash", "-c"]

# standard update/upgrades
RUN apt-get update -y \
 && apt-get upgrade -y 

# install python and java
RUN apt-get install python3 python3-pip curl unzip vim openjdk-8-jre -y
# add aliases to shell
RUN echo 'alias python="python3"' >> .bashrc
RUN echo 'alias pip="pip3"' >> .bashrc
# update shell source
RUN . .bashrc

# install python modules
RUN pip install ipython3 numpy pandas
RUN echo 'alias ipython="ipython3"' >> .bashrc
# update shell source
RUN . .bashrc
# RUN cat .bashrc

# download hadoop binary
RUN curl http://mirror.metrocast.net/apache/hadoop/common/hadoop-3.1.2/hadoop-3.1.2.tar.gz -o hadoop-3.1.2.tar.gz
# download keys and asc for validation
RUN curl https://www.apache.org/dist/hadoop/common/KEYS -o KEYS
RUN curl https://www.apache.org/dist/hadoop/common/hadoop-3.1.2/hadoop-3.1.2.tar.gz.asc -o hadoop.asc
# import keys and verify checksum
RUN gpg --import KEYS
RUN gpg --verify hadoop.asc hadoop-3.1.2.tar.gz
# decompress hadoop build into /opt
RUN tar -xvzf hadoop-3.1.2.tar.gz -C /opt
# cleanup
RUN rm -rf hadoop-3.1.2.tar.gz
RUN rm KEYS
RUN rm hadoop.asc

# download spark binary without hadoop
RUN curl http://apache.osuosl.org/spark/spark-2.4.4/spark-2.4.4-bin-without-hadoop.tgz -o spark-2.4.4-bin-without-hadoop.tgz
# download keys and asc for validation
RUN curl https://www.apache.org/dist/spark/KEYS -o KEYS
RUN curl https://www.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-without-hadoop.tgz.asc -o spark.asc
# import keys and verify checksum
RUN gpg --import KEYS
RUN gpg --verify spark.asc spark-2.4.4-bin-without-hadoop.tgz
# decompress spark build into /opt
RUN tar -xvzf spark-2.4.4-bin-without-hadoop.tgz -C /opt
# cleanup
RUN rm -rf spark-2.4.4-bin-without-hadoop.tgz
RUN rm KEYS
RUN rm spark.asc


# make sure interactive container starts in bash
ENTRYPOINT /bin/bash